language: go

go:
  - 1.8.x

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - go get -u github.com/jessevdk/go-flags
  - go get -u github.com/ryanuber/columnize
  - go get -u github.com/gorilla/mux
  - go get -u github.com/Urethramancer/countries
  - go get -u github.com/Urethramancer/slog
  - go get -u golang.org/x/crypto/sha3
