language: go

go:
  - 1.8.x

install:
  - go get github.com/jessevdk/go-flags
  - go get github.com/ryanuber/columnize
  - go get github.com/gorilla/mux
  - go get github.com/Urethramancer/countries
  - go get github.com/Urethramancer/slog
  - go get golang.org/x/crypto/sha3
